require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 150
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '**/routes.rb'
Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/widget/messages_controller.rb'
    - 'app/controllers/dashboard_controller.rb'
    - 'app/controllers/widget_tests_controller.rb'
    - 'app/controllers/widgets_controller.rb'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
RSpec/NestedGroups:
  Enabled: true
  Max: 4
AllCops:
  Exclude:
    - db/*
    - bin/**/*
    - db/**/*
    - config/**/*
    - public/**/*
    - vendor/**/*
    - node_modules/**/*
    - lib/tasks/auto_annotate_models.rake
